[package]
name = "voip-client"
version = "1.0.30"
description = "Rádio Pelotense 99.5 FM"
authors = ["Cristian Raffi Cunha"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.7", features = ["shell-open", "fs-read-file", "updater"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
